export const teamData = [
  {
    name: "Bryan Aument",
    role: "Co-founder / Fullstack",
    avatarURL: "/assets/bryan-img.png",
    avatarFallback: "BA",
    avatarAlt: "@bryanam",
    intro:
      "I build user focused web tools and applications. I'm learning Korean and Japanese, enjoy travel, connecting with people, and asolid cup of coffee sauce.",
    linkedinURL: "https://www.linkedin.com/in/bryanaument/",
    githubURL: "https://github.com/BryanAM",
    websiteURL: "http://bryan-aument.surge.sh",
    websiteTag: "@bryan-aument",
    key: 1,
  },
  {
    name: "Nathan Knight",
    role: "Co-founder / Fullstack",
    avatarURL: "/assets/nathan-img.png",
    avatarFallback: "KN",
    avatarAlt: "@knightxthyme",
    intro: "Language and music lover. Technology and science enthusiast.",
    linkedinURL: "https://www.linkedin.com/in/nathan-d-knight/",
    githubURL: "https://github.com/knightxthyme",
    key: 2,
  },
  {
    name: "Moyai Fujimura",
    role: "UX Lead",
    avatarURL: "/assets/moyai-img.png",
    avatarFallback: "MF",
    avatarAlt: "@moyaifuji",
    intro:
      "I design experiences that resonate with user needs and align with business goals. Outside of design, I love to travel and explore the world!",
    linkedinURL: "https://www.linkedin.com/in/moyai-fujimura/",
    websiteURL: "https://www.moyaifujimura.com/",
    websiteTag: "@moyai-fujimura",
    key: 3,
  },
  {
    name: "Moonyoung Kang",
    role: "Computational Linguist / Engineer",
    avatarURL: "/assets/moonyoung-img.png",
    avatarFallback: "MK",
    avatarAlt: "@moonyoungkang",
    intro:
      "I'm a computational linguist, programmer, and native Korean speaker. I believe language is the bridge that connects us to others, and I hope to help expand and strengthen that connection.",
    linkedinURL: "https://www.linkedin.com/in/moonyoungkang/",
    githubURL: "https://github.com/yerihyo",
    key: 4,
  },
];
